### ISSUE TITLE
Disable Login Form if Local Endpoint is Being Used

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#52]
Due to confusion, the option to show the Login With Domain on the WordPress login page shouldn't be available if you are using the local endpoint.

**Comment by pfefferle** [comment]
No, it shouldn't! I can login using my own IndieAuth server!

**Comment by pfefferle** [comment]
We shouldn't mix up IndieAuth with RelMe auth!

**Comment by dshanske** [comment]
You want to log in to a WordPress site that has its own local endpoint with that endpoint?

**Comment by pfefferle** [comment]
no, but with another website! i want to use pfefferle.org as my auth server and log into notiz.blog!

**Comment by dshanske** [comment]
Yes. So, the login form would be enabled on notiz.blog, but disabled on pfefferle.org

**Comment by pfefferle** [comment]
As I said we should not mix up IndieAuth with RelMeAuth!

**Comment by dshanske** [comment]
notiz.blog would have the endpoint setting of 'custom'. pfefferle.org would have 'local'.

**Comment by pfefferle** [comment]
why? I also want to use a local endpoint for notiz.blog to log into other sites!

**Comment by dshanske** [comment]
Okay. Didn't consider that. Point taken.

**Comment by dshanske** [comment]
Then I'll go with adding documentation to the settings page.

**Comment by dshanske** [comment]
But I'll likely fiddle with how the settings are displayed and behave to try and avoid newcomers being confused.

**Comment by pfefferle** [comment]
Perhaps we should add an explicit form for IndieAuth.com/RelMeAuth.

**Comment by dshanske** [comment]
The login form is a template, and has a action hook....I'm sure we could add text for Indieauth.com linking to an explanation.

**Comment by aaronpk** [comment]
While you're at it, would you like to switch over to indielogin.com instead of indieauth.com? The flow there is much better, although I haven't finished email and PGP auth yet. You can try out a demo of what it's like to log in using indielogin.com here: https://pin13.net/login/ If you have a custom authorization endpoint set for your domain, you shouldn't even see indielogin.com at all.

**Comment by dshanske** [comment]
@aaronpk Is there a config guide for that?

**Comment by aaronpk** [comment]
The API docs are here: https://indielogin.com/api (it's almost exactly the same as indieauth.com for this use case)

I haven't opened up indielogin.com for general use yet since it's still in progress, that's why you're seeing the client_id error. If you're interested, I can whitelist a few domain names for you to test with for now.

**Comment by dshanske** [comment]
Closing this as no longer relevant.
