### ISSUE TITLE
Local Auth Client does not work any more (2.0.3)

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieauth#57]
Sorry, but it seems that I haven't tested all the changes properly before.

The local client seems to be broken with the latest changes. If I try to login to my site, I get an error:

```
Invalid authorization code
```

**Comment by dshanske** [comment]
I didn't test that. I only tested login via Micropub

**Comment by aaronpk** [comment]
Remember when I tried to get you to document all the use cases on https://indieweb.org/Wordpress_IndieAuth_Plugin? I don't know why they were all deleted. That was for exactly this reason, so that we would have a list of use cases to test whenever we made a change. Can one of you please write up all the ways in which this plugin is used so that we have an actual list to test against?

**Comment by dshanske** [comment]
I will be fixing that

**Comment by dshanske** [comment]
I think I fixed this. I was able to simulate the outlined use case.
